In [4]:
import pandas as pd
df = pd.read_excel('http://taanila.fi/kunnat.xlsx', sheet_name='Kuntien avainluvut')
df.head()

,Kunta,"Taajama-aste, %, 2017","Väkiluku, 2017","Väkiluvun muutos edellisestä vuodesta, %, 2017","Alle 15-vuotiaiden osuus väestöstä, %, 2017","15-64 -vuotiaiden osuus väestöstä, %, 2017","Yli 64-vuotiaiden osuus väestöstä, %, 2017","Ruotsinkielisten osuus väestöstä, %, 2017","Ulkomaan kansalaisten osuus väestöstä, %, 2017","Syntyneiden enemmyys, henkilöä, 2017",...,"Taloudellinen huoltosuhde, 2016","Alueella olevien työpaikkojen lukumäärä, 2016","Alkutuotannon työpaikkojen osuus, %, 2016","Jalostuksen työpaikkojen osuus, %, 2016","Palvelujen työpaikkojen osuus, %, 2016","Vuosikate, euroa/asukas, 2017","Lainakanta, euroa/asukas, 2017","Konsernin lainakanta, euroa/asukas, 2017","Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017","Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017"
0,Akaa,88.5,16769,-0.9,18.0,59.8,22.2,0.2,1.6,-47,...,154.2,4512,3.3,35.6,59.5,370.2,3139.1,3927.7,1579.9,3231.2
1,Alajärvi,60.7,9831,-0.7,17.7,55.7,26.6,0.1,1.9,-19,...,187.7,3330,11.6,26.4,59.9,674.0,2152.1,4235.1,2152.6,3579.3
2,Alavieska,52.6,2610,-1.1,19.6,57.3,23.1,0.2,0.6,-5,...,169.3,741,24.4,21.6,52.0,276.2,2988.9,3182.4,1837.5,3995.8
3,Alavus,59.5,11713,-1.6,17.0,56.3,26.6,0.1,1.1,-42,...,172.1,4355,9.9,23.3,65.6,466.4,3307.6,6004.2,1780.8,3886.5
4,Asikkala,64.4,8248,-0.9,14.2,54.7,31.1,0.2,1.6,-51,...,171.7,2318,9.4,27.4,60.8,577.5,1453.7,3014.4,1607.9,3476.6

In [5]:
df.columns

Index(['Kunta', 'Taajama-aste, %, 2017', 'Väkiluku, 2017',
       'Väkiluvun muutos edellisestä vuodesta, %, 2017',
       'Alle 15-vuotiaiden osuus väestöstä, %, 2017',
       '15-64 -vuotiaiden osuus väestöstä, %, 2017',
       'Yli 64-vuotiaiden osuus väestöstä, %, 2017',
       'Ruotsinkielisten osuus väestöstä, %, 2017',
       'Ulkomaan kansalaisten osuus väestöstä, %, 2017',
       'Syntyneiden enemmyys, henkilöä, 2017',
       'Kuntien välinen muuttovoitto/-tappio, henkilöä, 2017',
       'Perheiden lukumäärä, 2017', 'Asuntokuntien lukumäärä, 2017',
       'Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2017',
       'Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2017',
       'Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Alueella asuvan työllisen työvoiman määrä, 2016',
       'Työllisyysaste, %, 2016',
       'Asuinkunnassaan työssäkäyvien osuus, %, 2016',
       'Työttömien osuus työvoimasta, %, 2016',
       'Eläkeläisten osuus väestöstä, %, 2016',
       'Taloudellinen huoltosuhde, 2016',
       'Alueella olevien työpaikkojen lukumäärä, 2016',
       'Alkutuotannon työpaikkojen osuus, %, 2016',
       'Jalostuksen työpaikkojen osuus, %, 2016',
       'Palvelujen työpaikkojen osuus, %, 2016',
       'Vuosikate, euroa/asukas, 2017', 'Lainakanta, euroa/asukas, 2017',
       'Konsernin lainakanta, euroa/asukas, 2017',
       'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017',
       'Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017'],
      dtype='object')

In [9]:
df.count()

Kunta                                                                                     311
Taajama-aste, %, 2017                                                                     311
Väkiluku, 2017                                                                            311
Väkiluvun muutos edellisestä vuodesta, %, 2017                                            311
Alle 15-vuotiaiden osuus väestöstä, %, 2017                                               311
15-64 -vuotiaiden osuus väestöstä, %, 2017                                                311
Yli 64-vuotiaiden osuus väestöstä, %, 2017                                                311
Ruotsinkielisten osuus väestöstä, %, 2017                                                 311
Ulkomaan kansalaisten osuus väestöstä, %, 2017                                            311
Syntyneiden enemmyys, henkilöä, 2017                                                      311
Kuntien välinen muuttovoitto/-tappio, henkilöä, 2017                                      311
Perheiden lukumäärä, 2017                                                                 311
Asuntokuntien lukumäärä, 2017                                                             311
Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2017                                311
Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2017                                    311
Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017    311
Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017              311
Alueella asuvan työllisen työvoiman määrä, 2016                                           311
Työllisyysaste, %, 2016                                                                   311
Asuinkunnassaan työssäkäyvien osuus, %, 2016                                              311
Työttömien osuus työvoimasta, %, 2016                                                     311
Eläkeläisten osuus väestöstä, %, 2016                                                     311
Taloudellinen huoltosuhde, 2016                                                           311
Alueella olevien työpaikkojen lukumäärä, 2016                                             311
Alkutuotannon työpaikkojen osuus, %, 2016                                                 311
Jalostuksen työpaikkojen osuus, %, 2016                                                   311
Palvelujen työpaikkojen osuus, %, 2016                                                    311
Vuosikate, euroa/asukas, 2017                                                             311
Lainakanta, euroa/asukas, 2017                                                            311
Konsernin lainakanta, euroa/asukas, 2017                                                  311
Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017        311
Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017        311
dtype: int64

In [11]:
df.shape

(311, 32)

In [13]:
#uusi muuttuja
bins=[2500, 5000 , 7500 ,10000, 12500, 15000, 17500, 20000]
df['asukaslukuluokka'] = pd.cut(df['Väkiluku, 2017'],bins=bins)
df.head()

,Kunta,"Taajama-aste, %, 2017","Väkiluku, 2017","Väkiluvun muutos edellisestä vuodesta, %, 2017","Alle 15-vuotiaiden osuus väestöstä, %, 2017","15-64 -vuotiaiden osuus väestöstä, %, 2017","Yli 64-vuotiaiden osuus väestöstä, %, 2017","Ruotsinkielisten osuus väestöstä, %, 2017","Ulkomaan kansalaisten osuus väestöstä, %, 2017","Syntyneiden enemmyys, henkilöä, 2017",...,"Alueella olevien työpaikkojen lukumäärä, 2016","Alkutuotannon työpaikkojen osuus, %, 2016","Jalostuksen työpaikkojen osuus, %, 2016","Palvelujen työpaikkojen osuus, %, 2016","Vuosikate, euroa/asukas, 2017","Lainakanta, euroa/asukas, 2017","Konsernin lainakanta, euroa/asukas, 2017","Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017","Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017",asukaslukuluokka
0,Akaa,88.5,16769,-0.9,18.0,59.8,22.2,0.2,1.6,-47,...,4512,3.3,35.6,59.5,370.2,3139.1,3927.7,1579.9,3231.2,"(15000, 17500]"
1,Alajärvi,60.7,9831,-0.7,17.7,55.7,26.6,0.1,1.9,-19,...,3330,11.6,26.4,59.9,674.0,2152.1,4235.1,2152.6,3579.3,"(7500, 10000]"
2,Alavieska,52.6,2610,-1.1,19.6,57.3,23.1,0.2,0.6,-5,...,741,24.4,21.6,52.0,276.2,2988.9,3182.4,1837.5,3995.8,"(2500, 5000]"
3,Alavus,59.5,11713,-1.6,17.0,56.3,26.6,0.1,1.1,-42,...,4355,9.9,23.3,65.6,466.4,3307.6,6004.2,1780.8,3886.5,"(10000, 12500]"
4,Asikkala,64.4,8248,-0.9,14.2,54.7,31.1,0.2,1.6,-51,...,2318,9.4,27.4,60.8,577.5,1453.7,3014.4,1607.9,3476.6,"(7500, 10000]"

In [21]:
#nimien vaihtoa
df.rename(columns = {'Alkutuotannon työpaikkojen osuus, %, 2016': 'alkutuotanto'
                     ,'Jalostuksen työpaikkojen osuus, %, 2016': 'jalostus'
                    , 'Palvelujen työpaikkojen osuus, %, 2016': 'palvelut'}, inplace = True)
df.head()

,Kunta,"Taajama-aste, %, 2017","Väkiluku, 2017","Väkiluvun muutos edellisestä vuodesta, %, 2017","Alle 15-vuotiaiden osuus väestöstä, %, 2017","15-64 -vuotiaiden osuus väestöstä, %, 2017","Yli 64-vuotiaiden osuus väestöstä, %, 2017","Ruotsinkielisten osuus väestöstä, %, 2017","Ulkomaan kansalaisten osuus väestöstä, %, 2017","Syntyneiden enemmyys, henkilöä, 2017",...,alkutuotanto,jalostus,palvelut,"Vuosikate, euroa/asukas, 2017","Lainakanta, euroa/asukas, 2017","Konsernin lainakanta, euroa/asukas, 2017","Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017","Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017",asukaslukuluokka,keskiarvo
0,Akaa,88.5,16769,-0.9,18.0,59.8,22.2,0.2,1.6,-47,...,3.3,35.6,59.5,370.2,3139.1,3927.7,1579.9,3231.2,"(15000, 17500]",32.800000
1,Alajärvi,60.7,9831,-0.7,17.7,55.7,26.6,0.1,1.9,-19,...,11.6,26.4,59.9,674.0,2152.1,4235.1,2152.6,3579.3,"(7500, 10000]",32.633333
2,Alavieska,52.6,2610,-1.1,19.6,57.3,23.1,0.2,0.6,-5,...,24.4,21.6,52.0,276.2,2988.9,3182.4,1837.5,3995.8,"(2500, 5000]",32.666667
3,Alavus,59.5,11713,-1.6,17.0,56.3,26.6,0.1,1.1,-42,...,9.9,23.3,65.6,466.4,3307.6,6004.2,1780.8,3886.5,"(10000, 12500]",32.933333
4,Asikkala,64.4,8248,-0.9,14.2,54.7,31.1,0.2,1.6,-51,...,9.4,27.4,60.8,577.5,1453.7,3014.4,1607.9,3476.6,"(7500, 10000]",32.533333

In [24]:
#keskiarvot työpaikkojen osuudesta
df['keskiarvo'] = df[['alkutuotanto',
                      'jalostus',
                      'palvelut']].mean(axis=1)
df[['keskiarvo','Kunta']]

     keskiarvo          Kunta
0    32.800000           Akaa
1    32.633333       Alajärvi
2    32.666667      Alavieska
3    32.933333         Alavus
4    32.533333       Asikkala
5    32.633333         Askola
6    32.466667           Aura
7    30.833333         Brändö
8    30.400000         Eckerö
9    32.466667      Enonkoski
10   32.233333      Enontekiö
11   32.933333          Espoo
12   32.900000           Eura
13   33.000000       Eurajoki
14   32.700000       Evijärvi
15   31.833333       Finström
16   33.066667         Forssa
17   32.033333          Föglö
18   30.466667           Geta
19   32.833333     Haapajärvi
20   32.933333      Haapavesi
21   32.800000       Hailuoto
22   32.600000         Halsua
23   32.800000         Hamina
24   30.166667     Hammarland
25   32.633333     Hankasalmi
26   33.000000          Hanko
27   33.133333     Harjavalta
28   32.833333        Hartola
29   32.666667        Hattula
..         ...            ...
281  32.366667         Urjala
282  32.733333       Utajärvi
283  30.633333        Utsjoki
284  32.800000       Uurainen
285  32.933333  Uusikaarlepyy
286  33.100000   Uusikaupunki
287  32.800000          Vaala
288  33.100000          Vaasa
289  33.066667    Valkeakoski
290  32.600000        Valtimo
291  33.066667         Vantaa
292  33.033333        Varkaus
293  32.666667         Vehmaa
294  32.766667        Vesanto
295  31.966667      Vesilahti
296  32.866667         Veteli
297  33.066667        Vieremä
298  32.800000          Vihti
299  32.900000     Viitasaari
300  32.633333        Vimpeli
301  32.933333      Virolahti
302  32.800000         Virrat
303  30.600000          Vårdö
304  32.900000          Vöyri
305  31.366667      Ylitornio
306  32.933333      Ylivieska
307  32.666667       Ylöjärvi
308  32.600000          Ypäjä
309  32.900000         Ähtäri
310  32.900000      Äänekoski

[311 rows x 2 columns]

In [36]:
#suodatuksia, ne joissa väkiluku yli 20000, järjestys myös vaihdettu
df[df['Väkiluku, 2017']>20000].sort_values(by='Väkiluku, 2017', ascending=False).head(20)

,Kunta,"Taajama-aste, %, 2017","Väkiluku, 2017","Väkiluvun muutos edellisestä vuodesta, %, 2017","Alle 15-vuotiaiden osuus väestöstä, %, 2017","15-64 -vuotiaiden osuus väestöstä, %, 2017","Yli 64-vuotiaiden osuus väestöstä, %, 2017","Ruotsinkielisten osuus väestöstä, %, 2017","Ulkomaan kansalaisten osuus väestöstä, %, 2017","Syntyneiden enemmyys, henkilöä, 2017",...,alkutuotanto,jalostus,palvelut,"Vuosikate, euroa/asukas, 2017","Lainakanta, euroa/asukas, 2017","Konsernin lainakanta, euroa/asukas, 2017","Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017","Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017",asukaslukuluokka,keskiarvo
33,Helsinki,100.0,643272,1.3,14.3,68.9,16.8,5.7,9.5,1524,...,0.1,10.1,88.9,1302.6,1874.7,7749.1,1924.7,2954.5,NaN,33.033333
11,Espoo,99.5,279044,1.6,19.4,66.2,14.5,7.2,10.5,1649,...,0.1,15.8,82.9,827.6,2887.0,12290.8,2384.0,2574.2,NaN,32.933333
268,Tampere,98.6,231853,1.6,13.7,67.5,18.8,0.5,4.6,376,...,0.2,18.6,80.3,367.1,2276.2,6273.9,2009.8,3245.6,NaN,33.033333
291,Vantaa,99.7,223027,1.7,17.8,67.0,15.2,2.5,11.2,1149,...,0.3,21.5,77.4,735.4,4517.0,8836.9,1942.2,2661.7,NaN,33.066667
180,Oulu,96.4,201810,0.6,18.8,65.9,15.3,0.2,2.9,944,...,0.7,18.9,79.4,590.5,3134.6,4004.1,1941.7,2964.4,NaN,33.000000
276,Turku,99.0,189669,1.1,12.9,66.7,20.5,5.4,6.5,-10,...,0.4,16.2,82.4,206.0,3991.5,7296.5,1880.1,3284.9,NaN,33.000000
63,Jyväskylä,94.7,140188,1.0,15.9,66.4,17.7,0.2,3.3,321,...,0.7,17.7,80.5,478.6,2609.7,7386.3,1711.7,2905.6,NaN,32.966667
123,Lahti,97.4,119573,0.1,14.7,61.8,23.5,0.4,4.3,-181,...,0.5,24.7,73.8,507.5,6314.3,9182.9,1761.5,3110.6,NaN,33.000000
114,Kuopio,85.7,118209,0.4,15.0,64.6,20.4,0.1,2.5,-55,...,2.9,13.9,82.1,486.6,2790.0,8013.1,1894.6,3418.1,NaN,32.966667
201,Pori,93.6,84587,-0.6,14.5,60.6,25.0,0.5,2.3,-316,...,1.4,21.8,75.8,483.6,2878.7,5339.6,1697.6,3249.8,NaN,33.000000
108,Kouvola,86.0,84196,-1.3,13.9,59.6,26.5,0.4,2.7,-470,...,3.6,21.6,73.6,269.3,2372.0,4118.0,2062.5,3586.0,NaN,32.933333
55,Joensuu,89.1,76067,0.3,14.0,65.0,21.0,0.1,3.1,-64,...,1.8,20.6,76.7,544.8,3008.9,6389.6,1745.0,3173.8,NaN,33.033333
129,Lappeenranta,89.9,72909,0.1,14.4,62.9,22.7,0.2,4.5,-163,...,1.8,21.8,75.5,455.5,2990.6,6865.0,1669.9,3353.7,NaN,33.033333
42,Hämeenlinna,87.7,67662,-0.3,15.1,60.3,24.6,0.3,3.7,-162,...,2.7,21.3,74.9,346.3,3284.9,6300.2,1678.7,3428.8,NaN,32.966667
288,Vaasa,98.0,67392,-0.3,15.9,64.6,19.5,22.8,6.0,-3,...,0.5,27.4,71.4,474.3,3836.1,8256.0,2407.0,3282.4,NaN,33.100000
243,Seinäjoki,90.8,62676,1.0,17.8,63.3,18.9,0.2,1.7,228,...,2.3,22.2,74.6,465.5,4252.2,8582.5,1934.6,2975.0,NaN,33.033333
229,Rovaniemi,89.7,62420,0.3,16.5,64.9,18.5,0.2,2.5,73,...,2.2,13.0,83.5,267.6,2470.5,3650.4,1901.5,3290.4,NaN,32.900000
157,Mikkeli,80.0,54261,-0.5,14.3,60.6,25.0,0.1,2.4,-183,...,3.2,19.0,76.7,491.4,3643.6,9311.0,1882.9,3360.3,NaN,32.966667
107,Kotka,98.2,53539,-1.2,13.8,60.5,25.7,1.0,6.1,-309,...,0.6,21.5,76.9,539.6,5615.8,10465.4,1758.7,3902.7,NaN,33.000000
236,Salo,75.0,52984,-1.0,15.1,59.3,25.6,1.1,3.9,-289,...,5.4,25.8,67.4,421.7,1652.0,2926.3,1766.7,3472.4,NaN,32.866667